### ISSUE TITLE
"Unknown Shorthand" when running minecraft_launcher

### ISSUE THREAD

**Issue by 4325123** [IMetZach/bedrock-server#10]
Thanks for making the updates to the shell script.  Unfortunately though, when I try to run it, I'm getting this error...

$ ./minecraft_launcher.sh --start creative
Creating World Directory and Files
unknown shorthand flag: 'd' in -d
See 'docker create --help'.
$

I'm not too great with docker, but I don't think the -d (for detached) works with docker create.  I didn't try to edit the script to take it out and see if it works without it or not.

**Comment by IMetZach** [comment]
From the docker docs, it appears that containers start in detached mode so I removed the ```-d``` flag from the start script. Thank you for testing these changes out for me.

**Comment by 4325123** [comment]
> From the docker docs, it appears that containers start in detached mode so I removed the `-d` flag from the start script. Thank you for testing these changes out for me.

Thanks for the change.  I tried the updated script and it downloads everything now but doesn't start the instance up.

$ docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
482c5455c87b        imetzach/bedrock-server:latest    "/opt/minecraft/star…"   14 seconds ago      Created                                      creative

When trying to start the instance, I get the following error:

$ docker run 482c5455c87b
Unable to find image '482c5455c87b:latest' locally
docker: Error response from daemon: pull access denied for 482c5455c87b, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
$


***EDIT:****  Please ignore for now.  I modified the script a bit so that it adds a static IP on a specific network.  When I tried your original script that I didn't modify, it starts up fine.

**Comment by 4325123** [comment]
That was weird...  I ran your original script and it worked.  Then I tried to start my original instance that failed above and it started up.  Maybe it had to sync or something?  Don't know, but it looks like it's working now.

I'm also able to attach to the console and execute console commands.  Thank You for adding this in!!!
