### ISSUE TITLE
Repo not updated to 1.16.100.04

### ISSUE THREAD

**Issue by chaines** [IMetZach/bedrock-server#11]
Not a huge issue for me, since I can just manually update, but given that the readme states it would automatically update within 30 minutes, I figured it would be worth mentioning that the dockerfile in the readme is still on the last update, approx 30 hours after release.

**Comment by m1820** [comment]
My kiddos haven’t been able to play since the update :) how did you manually update the server ?

**Comment by IMetZach** [comment]
Hey. Sorry for the lack of a response. Microsoft updated their website which broke my automation and then my server that was running all the automation lost it's HDD, I just updated it manually to the latest which is 1.16.101.01
